<?xml version='1.0'?>
<package format='3'>
  <name>hpp_pinocchio</name>
  <version>9.0.2</version>
  <description>Wrapping of the kinematic/dynamic chain Pinocchio for HPP</description>
  <author>Joseph Mirabel</author>
  <author>Florent Lamiraux</author>
  <maintainer email='guilhem.saurel@laas.fr'>Guilhem Saurel</maintainer>

  <license>BSD-2-Clause</license>

  <url type="website">https://github.com/humanoid-path-planner/hpp-pinocchio</url>
  <url type="repository">https://github.com/humanoid-path-planner/hpp-pinocchio</url>
  <url type="bugtracker">https://github.com/humanoid-path-planner/hpp-pinocchio/issues</url>

  <depend>coal</depend>
  <depend>boost</depend>
  <depend>eigen</depend>
  <depend>example_robot_data</depend>
  <depend>hpp_environments</depend>
  <depend>hpp_util</depend>
  <depend>pinocchio</depend>
  <depend>urdfdom</depend>

  <buildtool_depend>cmake</buildtool_depend>
  <build_depend>doxygen</build_depend>
  <build_depend>jrl_cmakemodules</build_depend>

  <export>
    <build_type>cmake</build_type>
  </export>
</package>
