[build-system]
build-backend = "cmeel"
requires = [
  "cmeel-boost ~= 1.90.0",
  "cmeel[build]",
  "example-robot-data[build]",
  "hpp-environments[build]",
  "hpp-util[build]",
  "pin[build]"
]

[project]
dependencies = [
  "cmeel-boost ~= 1.90.0",
  "example-robot-data",
  "hpp-environments",
  "hpp-util",
  "pin"
]
description = "Wrapping of the kinematic/dynamic chain Pinocchio for HPP"
license = "BSD-2-Clause"
name = "hpp-pinocchio"
requires-python = ">= 3.10"
version = "9.0.0"

[tool.ruff]
extend-exclude = ["cmake"]

[tool.ruff.lint]
extend-select = ["I", "NPY", "RUF", "UP", "W"]

[tool.tomlsort]
all = true
